<?php
/*
 * Version: 150607
 * */
QdT_Library::loadLayoutClass('root');

class QdT_PageT_ConfirmOrderMobile extends QdT_Layout_Root
{
    public $product = null;

    public $product_order_setup = null;

    function __construct()
    {
        parent::__construct();

        $this->product_order_setup = QdSetupProductOrder::GET();
        $this->product = QdProduct::GET(get_query_var('id', 0));
        if ($this->product == null) static::redirectPageError404();//check resource

    }


    public function loadScript()
    {
        QdJqwidgets::loadSinglePluginJS("form2js.js");
        QdJqwidgets::loadSinglePluginJS("js.cookie.js");
    }

    public function setPageInfoToClient()
    {
        parent::setPageInfoToClient(); // TODO: Change the autogenerated stub
        ?>
        <script>
            MYAPP.PageInfo.product_order_setup = <?=json_encode(QdSetupProductOrder::toJSON(array($this->product_order_setup)))?>;
            MYAPP.PageInfo.product_obj = <?=json_encode(QdProduct::toJSON(array($this->product)))?>;
        </script>
    <?php
    }

    public static function getPageName()
    {
        return 'confirm-order-mobile';
    }

    public static function getPageViewMobileClass()
    {
        return 'QdT_PageT_ConfirmOrder_ViewMobile';
    }
}