<?php
/**
 * Created by PhpStorm.
 * User: quocd_000
 * Date: 24/06/2015
 * Time: 9:54 PM
 */
QdT_Library::loadLayoutView('introduction');
class QdT_PageT_Service_View extends QdCPT_IntroductionLayout_View{

    protected function getContentMain()
    {
        return $this->page->obj->content;
    }
    protected function getContentTitle()
    {
        return $this->page->obj->title;
    }
    protected function getBreadcrumbs()
    {
        $tmp = parent::getBreadcrumbs(); // TODO: Change the autogenerated stub
        $tmp = array_merge($tmp, $this->page->obj->getBreadcrumbs());
        return $tmp;
    }
}