<?php

QdT_Library::loadLayout('root');

class QdT_PageT_ProductDetail extends QdT_Layout_Root
{
    private $product = null;
    private $r_products = array();
    private $product_imgs = array();
    private $size = null;
    private $cookie_customer = array();

    private $product_order_setup = null;

    function __construct()
    {
        parent::__construct();

        //get cookie
        if(isset($_COOKIE["customer"]))
        {
            $tmp = $_COOKIE["customer"];
            $tmp = str_replace('\\"', '"', $tmp);
            $this->cookie_customer = json_decode($tmp, true);
        }
        else
        {
            $this->cookie_customer = array();
        }


        $this->product_order_setup = QdSetupProductOrder::GET();
        $this->product = QdProduct::GET(get_query_var('id', 0));
        if ($this->product == null) static::redirectPageError404();//check resource


        $this->manufactor = QdManufactor::GET($this->product->manufacturer_id);

        //IMGS
        $tmp = $this->product->getImages();
        $tmp->SETRANGE('active', true);
        $tmp->SETORDERBY('order', 'asc');
        $this->product_imgs = $tmp->GETLIST();
        if (empty($this->product_imgs)) {
            $img_tmp = new QdImage();
            $img_tmp->path = $this->product->avatar;
            $img_tmp->active = true;
            array_push($this->product_imgs, $img_tmp);
        }
        //END IMGS

        $this->size = QdSize::GET($this->product->size_id);

        $this->r_products = $this->product->getRProducts2();

    }

    protected function getBannerPart()
    {
        //HIDE
    }

    protected function loadScript()
    {
        QdJqwidgets::loadSinglePluginJS("form2js.js");
        QdJqwidgets::loadSinglePluginJS("js.cookie.js");
        //QdJqwidgets::loadSinglePluginJS("ajax-loader.js");
    }

    protected function setPageInfoToClient()
    {
        parent::setPageInfoToClient(); // TODO: Change the autogenerated stub
        ?>
        <script>
            MYAPP.PageInfo.product_order_setup = <?=json_encode(QdSetupProductOrder::toJSON(array($this->product_order_setup)))?>;
            MYAPP.PageInfo.product_obj = <?=json_encode(QdProduct::toJSON(array($this->product)))?>;
        </script>
        <?php
    }

    private function dialog()
    {
        ?>

    <?php
    }

    protected function getContentPart()
    {
        ?>
        <?= $this->dialog() ?>
        <div class="container-non-responsive carousel content" style="margin-top: 0px">
        <div class="row">
            <div class="col-xs-12">
                <?= $this->getBreadcrumbsPart() ?></div>
        </div>

        <div class="row">

        <!--Left-->
        <div class="col-xs-7">
            <!-- Limited -->
            <div id="bigPic">
                <?php
                $count = 0;
                foreach ($this->product_imgs as $item):
                    ?>
                    <img src="<?= $item->path ?>" alt=""
                         style="display: <?= $count == 0 ? 'block' : 'none' ?>; opacity: 1; z-index: 1;">
                    <?php
                    $count++;
                endforeach; ?>
                <!--
                <img src="imgs/2.jpg" alt="" style="display: block; opacity: 1; z-index: 1;">
                <img src="imgs/3.jpg" alt="" style="display: none; opacity: 1; z-index: 1;">
                <img src="imgs/4.jpg" alt="" style="display: none; opacity: 1; z-index: 1;">
                <img src="imgs/5.jpg" alt="" style="display: none; opacity: 1; z-index: 1;">
                <img src="imgs/6.jpg" alt="" style="display: none; opacity: 1; z-index: 1;">
                <img src="imgs/7.jpg" alt="" style="display: none; opacity: 1; z-index: 1;">
                <img src="imgs/8.jpg" alt="" style="display: none; opacity: 1; z-index: 1;">
                <img src="imgs/9.jpg" alt="" style="display: none; opacity: 1; z-index: 1;">
                <img src="imgs/10.jpg" alt="" style="display: none; opacity: 1; z-index: 1;"> -->
            </div>


            <ul id="thumbs">
                <?php
                $count = 1;
                foreach ($this->product_imgs as $item):
                    ?>
                    <li rel="<?= $count ?>" class=""><img src="<?= $item->path ?>" alt=""></li>
                    <?php
                    $count++;
                endforeach; ?>
                <!--
                <li rel="2" class="active"><img src="imgs/3_thumb.jpg" alt=""></li>
                <li rel="3" class=""><img src="imgs/4_thumb.jpg" alt=""></li>
                <li rel="4" class=""><img src="imgs/5_thumb.jpg" alt=""></li>
                <li rel="5" class=""><img src="imgs/6_thumb.jpg" alt=""></li>
                <li rel="6" class=""><img src="imgs/7_thumb.jpg" alt=""></li>
                <li rel="7" class=""><img src="imgs/8_thumb.jpg" alt=""></li>
                <li rel="8" class=""><img src="imgs/9_thumb.jpg" alt=""></li>
                <li rel="9" class=""><img src="imgs/10_thumb.jpg" alt=""></li>
                <li rel="10" class=""><img src="imgs/2_thumb.jpg" alt=""></li> -->
            </ul>

            <!-- Limited -->
        </div>

        <!--Right-->
        <div class="col-xs-5 product-detail-right">
        <div class="row">
            <div class="col-xs-12">
                <div class="vn-title">
                    <?= $this->product->name ?>
                </div>
            </div>
        </div>

        <!-- detail product 1-->
        <div class="row">
            <div class="col-xs-12">
                <?php if (!QdT_Library::isNullOrEmpty($this->product) && $this->product->code != ''): ?>
                    <div class="vn-model">
                        <div class="title">
                            No.
                        </div>
                        <div class="id">
                            <?= $this->product->code ?>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if (!QdT_Library::isNullOrEmpty($this->manufactor) && $this->manufactor->name != ''): ?>
                    <div class="vn-symbol">|</div>
                    <div class="vn-hang">
                        <div class="title">
                            Hãng :
                        </div>
                        <div class="id">
                            <?= $this->manufactor->name ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <!-- detail product 2-->
        <div class="row price-tag">
            <div class="col-xs-12">
                <div class="price">
                    <?= number_format($this->product->price, 0, '.', ',') ?> VND
                </div>

                <?php if (!QdT_Library::isNullOrEmpty($this->size) && $this->size->code != ''): ?>
                    <div class="vn-symbol">|</div>
                    <div class="size">
                        <?= $this->size->code ?>
                    </div>
                <?php endif; ?>

                <?php if (!QdT_Library::isNullOrEmpty($this->product) && $this->product->discount_percent > 0): ?>
                    <div class="vn-symbol">|</div>
                    <div class="off">
                        <?= number_format($this->product->_price_discount, 0, '.', ',') ?> VND
                        (<?= $this->product->discount_percent * 100 ?>% OFF)
                    </div>
                <?php endif; ?>

                <?php if (!QdT_Library::isNullOrEmpty($this->product) && ($this->product->temp_out_of_stock == true)): ?>
                    <div class="vn-symbol">|</div>
                    <div class="state">
                        Tạm hết hàng
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <hr style="margin-top: 5px; margin-bottom: 10px;">

        <!-- Detail -->
        <div class="row">
            <div class="col-xs-12">
                <div class="vn-product-detail">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#mo-ta">MÔ TẢ SẢN PHẨM</a></li>
                        <li>
                            <div class="vn-symbol">|</div>
                        </li>
                        <li><a data-toggle="tab" href="#bao-hanh">ĐỔI TRẢ - BẢO HÀNH</a></li>
                        <li>
                            <div class="vn-symbol">|</div>
                        </li>
                        <li><a data-toggle="tab" href="#giao-hang">GIAO HÀNG VÀ THANH TOÁN</a></li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div id="mo-ta" class="tab-pane fade in active" style="margin-top: 15px;">
                        <?= $this->product->description ?>
                        <!-- <div class="ps"> ĐẶT MUA TẶNG: bAO DA KAKA TRỊ GIÁ 300K !</div> -->
                    </div>
                    <div id="bao-hanh" class="tab-pane fade" style="margin-top: 15px;">
                        <?= $this->product->doitra_baohanh ?>
                    </div>
                    <div id="giao-hang" class="tab-pane fade" style="margin-top: 15px;">
                        <?= $this->product->giaohang_thanhtoan ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- Button đặt hàng -->
        <div class="row">
            <div class="col-xs-6" data-role="main">
                <button type="button" class="btn btn-primary order-online-button" data-toggle="modal"
                        data-target="#myModal"> <?=$this->product_order_setup->btn_dathang?>
                </button>

                <!-- Modal -->
                <div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog"
                     aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                        aria-hidden="true">×</span></button>
                                <div class="vn-modal-title"><?=$this->product_order_setup->order_form_title?></div>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-xs-5" style="height:450px;">
                                        <div>
                                            <div class="vn-sanpham-box-modal"
                                                 style="background: url('<?= $this->product->avatar ?>');
                                                     background-repeat: no-repeat;
                                                     background-size: contain;
                                                     background-position: center;">
                                            </div>
                                            <p class="p-edit-1">
                                                <?= $this->product->name ?>
                                            </p>

                                            <p class="p-edit-1">
                                                <b style="color: rgb(131,131,132);font-weight: normal;">
                                                    <?= number_format($this->product->price, 0, '.', ',') ?>
                                                    VND</b>
                                                <img src="img/border-links.png" style="margin: 0px 5px;"> <b>L</b>
                                                <br>
                                                <b style="color: #C80815;">
                                                    <?= number_format($this->product->_price_discount, 0, '.', ',') ?>
                                                    VND (<?= $this->product->discount_percent * 100 ?>% OFF)
                                                </b>
                                            </p>
                                        </div>
                                        <div style="position: absolute;bottom: 15px;left: 15px;font-size: 16px; ">
                                            <?=$this->product_order_setup->support_phone?>
                                        </div>
                                    </div>
                                    <div class="col-xs-7">
                                        <form id="formOrder" onsubmit="return false">
                                            <input type="hidden" name="product_id"
                                                   value="<?= $this->product->id ?>">
                                            <input type="hidden" name="count"
                                                   value="1">

                                            <div class="row">
                                                <?php
                                                if(QdT_Library::isNullOrEmpty($this->cookie_customer['sex']))
                                                {
                                                    $this->cookie_customer['sex'] = "1";
                                                }
                                                ?>

                                                <div class="col-xs-6">
                                                    <input type="radio" name="sex" value="1" <?=$this->cookie_customer['sex']=="1"?"checked":""?>><label
                                                        style="margin-left: 5px;">Anh</label>
                                                </div>
                                                <div class="col-xs-6">
                                                    <input type="radio" name="sex" value="0" <?=$this->cookie_customer['sex']=="0"?"checked":""?>><label
                                                        style="margin-left: 5px;">Chị</label>
                                                </div>
                                            </div>
                                            <div class="control-group form-group">
                                                <div class="controls">
                                                    <input type="text" class="form-control" name="customer_name"
                                                           placeholder="Vui lòng nhập họ tên"
                                                           aria-invalid="false"
                                                           oninvalid="this.setCustomValidity('Họ tên bắt buộc nhập')"
                                                           oninput="this.setCustomValidity('')"
                                                           value="<?php
                                                           if(!QdT_Library::isNullOrEmpty($this->cookie_customer['customer_name']))
                                                           {
                                                               echo $this->cookie_customer['customer_name'];
                                                           }
                                                           ?>"
                                                           required autofocus>

                                                    <p class="help-block"></p>
                                                </div>
                                            </div>
                                            <div class="control-group form-group">
                                                <div class="controls">
                                                    <input type="text" class="form-control" name="customer_phone"
                                                           placeholder="Vui lòng nhập số điện thoại"
                                                           oninvalid="this.setCustomValidity('Số điện thoại bắt buộc nhập')"
                                                           oninput="this.setCustomValidity('')"
                                                           aria-invalid="false"
                                                           value="<?php
                                                           if(!QdT_Library::isNullOrEmpty($this->cookie_customer['customer_phone']))
                                                           {
                                                               echo $this->cookie_customer['customer_phone'];
                                                           }
                                                           ?>"
                                                           required>

                                                    <p class="help-block"></p>
                                                </div>
                                            </div>
                                            <div class="control-group form-group">
                                                <div class="controls">
                                                    <input type="text" class="form-control" name="customer_email"
                                                           placeholder="Vui lòng nhập Email (nếu có)"
                                                           oninvalid="this.setCustomValidity('Email bắt buộc nhập')"
                                                           oninput="this.setCustomValidity('')"
                                                           value="<?php
                                                           if(!QdT_Library::isNullOrEmpty($this->cookie_customer['customer_email']))
                                                           {
                                                               echo $this->cookie_customer['customer_email'];
                                                           }
                                                           ?>"
                                                           aria-invalid="false" required>

                                                    <p class="help-block"></p>
                                                </div>
                                            </div>
                                            <div class="control-group form-group">
                                                <div class="controls">
                                                    <textarea rows="10" cols="100" class="form-control" name="mota"
                                                              placeholder="Vui lòng ghi yêu cầu (nếu có)"
                                                              maxlength="999" style="resize:none"
                                                              aria-invalid="false"></textarea>

                                                    <p class="help-block"></p>
                                                </div>
                                            </div>

                                            <!-- <button type="button" class="btn btn-primary" data-toggle="modal"
                                                    data-target="#myModal1">XÁC NHẬN
                                            </button> -->
                                            <button id="formOrderDoneConfirm" type="submit" class="btn btn-primary">XÁC NHẬN
                                            </button>
                                            <script>
                                                MYAPP.PageInfo.DataPort = '<?=Qdmvc_Helper::getDataPortPath('front/product_order_port')?>';
                                                (function($){
                                                    $(document).ready(function(){
                                                        $('#formOrderDoneConfirm').click(function(){
                                                            //send data to DataPort
                                                            var json = form2js("formOrder", ".", false, null, true);
                                                            //validate
                                                            if(json.customer_name=='') return;
                                                            if(json.customer_phone=='') return;
                                                            if(json.customer_email=='') return;
                                                            if(json.sex=='') return;

                                                            console.log(json);
                                                            //save to cookie
                                                            Cookies.set('customer', json, { expires: 7 });
                                                            //lock button
                                                            $("#formOrderDoneConfirm").attr("disabled", true);

                                                            //show progress bar
                                                            //...
                                                            $.post(MYAPP.PageInfo.DataPort, {submit: "submit", action: "insert", data: json})
                                                                .done(function (data) {
                                                                    //data JSON
                                                                    console.log(data);
                                                                    //var obj = data;//"ok";//jQuery.parseJSON( data );//may throw error if data aldreay JSON format
                                                                    var customer_sex = $("#formOrder input:radio[name=sex]:checked" ).val();

                                                                    customer_sex = customer_sex == 1 ? "Anh" : (customer_sex == 0?"Chị":"");
                                                                    var customer_name = $("#formOrder input[name=customer_name]" ).val();
                                                                    //...
                                                                    //if OK
                                                                    var tpl = MYAPP.TplReplace(["{customer_title}","{customer_name}","{product_name}"], [customer_sex, customer_name, MYAPP.PageInfo.product_obj[0].name], MYAPP.PageInfo.product_order_setup[0].form_order_done_tpl);


                                                                    $("#formOrderDoneTpl").html(tpl);
                                                                    $("#myModal1").modal('show');

                                                                })
                                                                .fail(function (data) {
                                                                    console.log(data);
                                                                })
                                                                .always(function () {
                                                                    //release lock
                                                                    $("#formOrderDoneConfirm").removeAttr("disabled");
                                                                });
                                                        });
                                                    });
                                                })(jQuery);
                                            </script>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->

                <!-- Modal 2 -->
                <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                        aria-hidden="true">×</span></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-xs-7">
                                        <div class="vn-modal1-title"><?=$this->product_order_setup->form_order_done_title	?></div>
                                        <div id="formOrderDoneTpl" class="col-xs-12 column" style="margin-top: 15px;">

                                        </div>
                                    </div>
                                    <div class="col-xs-5">
                                        <div class="vn-nhanvien-box-modal" style="background: url('<?=$this->product_order_setup->form_order_done_avatar?>');
                                                          background-repeat: no-repeat;
                                                          background-size: contain;
                                                          background-position: center;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->

            </div>
            <div class="col-xs-6">
                <a class="btn btn-default order-phone-button" href="#myPopup" data-rel="popup">
                    <?=$this->product_order_setup->btn_goidathang?>
                </a>
            </div>

        </div>
        <hr style="margin-top: 5px; margin-bottom: 10px;">

        <!-- Shop hàng -->
        <div class="row">
            <div class="col-xs-8">
                MUA HÀNG TẠI SHOP
                <br>
                <a href="#" class="product-detail-shop">( xem Shop có hàng )</a>

            </div>
            <div class="col-xs-4">
                Share +
            </div>
        </div>
        </div>
        </div>
        <?= $this->render_r_products() ?>

        </div>
        <script>

            $('.carousel').carousel({
                interval: 5000 //changes the speed
            });


            var currentImage;
            var currentIndex = -1;
            var interval;
            function showImage(index) {
                if (index < $('#bigPic img').length) {
                    var indexImage = $('#bigPic img')[index]
                    if (currentImage) {
                        if (currentImage != indexImage) {
                            $(currentImage).css('z-index', 2);
                            clearTimeout(myTimer);
                            $(currentImage).fadeOut(250, function () {
                                myTimer = setTimeout("showNext()", 3000);
                                $(this).css({'display': 'none', 'z-index': 1})
                            });
                        }
                    }
                    $(indexImage).css({'display': 'block', 'opacity': 1});
                    currentImage = indexImage;
                    currentIndex = index;
                    $('#thumbs li').removeClass('active');
                    $($('#thumbs li')[index]).addClass('active');
                }
            }

            function showNext() {
                var len = $('#bigPic img').length;
                var next = currentIndex < (len - 1) ? currentIndex + 1 : 0;
                showImage(next);
            }

            var myTimer;

            $(document).ready(function () {
                myTimer = setTimeout("showNext()", 3000);
                showNext(); //loads first image
                $('#thumbs li').bind('click', function (e) {
                    var count = $(this).attr('rel');
                    showImage(parseInt(count) - 1);
                });
            });


        </script>

    <?php
    }

    protected function render_r_products()
    {
        if (empty($this->r_products)) return;
        ?>
        <!-- Có thể bạn thích -->
        <div class="row">
            <div class="col-xs-12">
                <h3 class="page-header">CÓ THỂ BẠN THÍCH</h3>
            </div>
        </div>

        <!-- Like 1-->
        <div class="row">
            <!-- <div class="col-xs-3">
                <div class="vn-sanpham-box" style="background: url('img/sanpham-index.png');
                                                          background-repeat: no-repeat;
                                                          background-size: contain;
                                                          background-position: center;">
                </div>
            </div> -->
            <?php
            $count = 1;
            foreach ($this->r_products as $item):
                static::genProductWidget($item, 'col-xs-3', '');
                if ($count % 4 == 0) echo '<div class="col-xs-12" style="height: 20px"></div>';//trick to avoid using new row and not overlap with other item
                $count++;
            endforeach;
            ?>
        </div>
    <?php
    }

    protected function getBreadcrumbs()
    {
        $tmp = parent::getBreadcrumbs();
        $tmp = array_merge($tmp, $this->product->getBreadcrumbs());
        return $tmp;
    }
}